---
services:
  app:
    build:
      context: .
      dockerfile: ./Docker/app/Dockerfile
    container_name: app
    environment:
      TZ: ${TIME_ZONE}
      COMPOSER_ALLOW_SUPERUSER: 1
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html
    networks:
      - backend

  web:
    image: nginx:${NGINX_TAG}
    container_name: web
    environment:
      TZ: ${TIME_ZONE}
    ports:
      - ${LOCAL_PORT}:80
    depends_on:
      - app
    volumes:
      - type: bind
        source: ./Docker/web/default.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: ./src
        target: /var/www/html
    networks:
      - backend

  db:
    image: mysql:8.0
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: ${ALLOW_EMPTY_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: ${TIME_ZONE}
    volumes:
      - type: volume
        source: laravel-data
        target: /var/lib/mysql
      - type: bind
        source: ./Docker/db/my.conf
        target: /etc/my.conf
    networks:
      - backend


volumes:
  laravel-data:

networks:
  backend:
