---
services:
  app:
    build:
      context: .
      dockerfile: ./Docker/app/Dockerfile
    container_name: app
    environment:
      TZ: Asia/Tokyo
      COMPOSER_ALLOW_SUPERUSER: 1
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html
    networks:
      - backend

  web:
    image: nginx:1.22
    container_name: web
    environment:
      TZ: Asia/Tokyo
    ports:
      - 8080:80
    depends_on:
      - app
    volumes:
      - type: bind
        source: ./Docker/web/default.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: ./src
        target: /var/www/html
    networks:
      - backend

  db:
    image: mysql:8.0
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    volumes:
      - type: volume
        source: laravel-data
        target: /var/lib/mysql
      - type: bind
        source: ./Docker/db/my.conf
        target: /etc/my.conf
    networks:
      - backend


volumes:
  laravel-data:

networks:
  backend:
